# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='add_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='添加日期'),
        ),
    ]
